### PR TITLE
Fix lesson description not updating after saving changes

### LINKED ISSUE #125: Editor: Lesson description not updating after saving changes
Go to the lesson editor and update a lesson's description. It does save the changes but the page doesn't show it unless we refresh the page.

### PR DESCRIPTION
**Pull request by Teslima02**
- Fixed lesson description not updating after saving changes
- fixes #125

### CODE REVIEW

**Comment by wceolin** [comment]
Thanks, @Teslima02. I'll review it later today. In the meantime, please can you add a test to make sure this is working as expected?

**Comment by Teslima02** [comment]
Yes I will.

**Comment by Teslima02** [comment]
> Thanks, @Teslima02. I'll review it later today. In the meantime, please can you add a test to make sure this is working as expected?

@wceolin I have added the test cases.

File: lib/dashboard/lessons/lesson_editor.ex [hunk 1]
```diff
@@ -176,6 +176,12 @@ defmodule UneebeeWeb.Live.Dashboard.LessonEditor do
     end
   end
 
+  @impl Phoenix.LiveView
+  def handle_info({LessonEdit, :lesson_edit, updated_socket}, socket) do
+    %{lesson: lesson} = updated_socket.assigns
+    {:noreply, assign(socket, lesson: lesson)}
+  end
```
Comment (wceolin) [inline lib/dashboard/lessons/lesson_editor.ex:183]: Even though this approach works, it adds some extra code that might be unnecessary because [we're navigating back to the page using push_patch](https://github.com/zoonk/uneebee/blob/d0ec9c696f06e509f59ffa71571b7d207a38ef42/lib/dashboard/lessons/components/lesson_edit.ex#L60). This means the [handle_params called is going to be called](https://github.com/zoonk/uneebee/blob/d0ec9c696f06e509f59ffa71571b7d207a38ef42/lib/dashboard/lessons/lesson_editor.ex#L30) and we already have the updated lesson data there because [we call Content.list_lessons/1](https://github.com/zoonk/uneebee/blob/d0ec9c696f06e509f59ffa71571b7d207a38ef42/lib/dashboard/lessons/lesson_editor.ex#L34).

Therefore, I suggest that we use this `lessons` list to find the updated lesson and assign it back to our socket:

```elixir
updated_lesson = Enum.find(lessons, fn l -> l.id == lesson.id end)
```

Then, add this to the socket assignments, you can just add a new line with the updated lesson

```elixir
assign(:lesson, updated_lesson)
```

What do you think? Does that make sense?

File: test/dashboard/lesson_editor_test.exs [hunk 2]
```diff
@@ -389,6 +389,29 @@ defmodule UneebeeWeb.DashboardLessonEditorLiveTest do
...
+        |> follow_redirect(conn, edit_lesson_redirect_link(course, lesson))
+
+      assert_lesson_name(view)
+      assert_lesson_description(view)
+
+      attrs = %{name: "Updated lesson name", description: "Updated lesson description"}
+      view |> form(@lesson_form, lesson: attrs) |> render_submit()
+
+      assert render(view) =~ "Updated lesson name"
+      assert render(view) =~ "Updated lesson description"
```
Comment (wceolin) [inline test/dashboard/lesson_editor_test.exs:412]: This can lead to a false positive in case the "Updated lesson name" text is present somewhere else in the page. For example, if you remove your changes you'll the first assertion (updated lesson name) actually passes, even though the feature is broken.

We can minimize this by using `has_element?/3` instead:

```suggestion
      assert has_element?(view, "h1", "Updated lesson name")
      assert has_element?(view, "p", "Updated lesson description")
```

**Review by wceolin — COMMENTED** [review]
Thank you for working on this! It works but I have two minor suggestions to make these changes more resilient. Please, let me know what you think.

File: lib/dashboard/lessons/lesson_editor.ex (hunk 1 above)
Comment (Teslima02) [reply lib/dashboard/lessons/lesson_editor.ex:183]: @wceolin This is an amazing review I have to go back and retrace my step, I agree with you using `push_patch` to navigate after saving the changes will push the updated state to the client without reloading the whole page and this makes the updated lesson object available on the client side. Thank you for the suggestions

File: test/dashboard/lesson_editor_test.exs (hunk 2 above)
Comment (Teslima02) [reply test/dashboard/lesson_editor_test.exs:412]: @wceolin Thank you for the update `has_element?/3` works better.

**Review by wceolin — APPROVED** [review]
Looks great! Thank you, @Teslima02
